spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bobbysoft_organizer
    username: admin
    password: admin
    schemas: bobbysoft_db
  jpa:
    defer-datasource-initialization: false
    show-sql: false
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: bobbysoft_db
  flyway:
    user: admin
    password: admin
    schemas: bobbysoft_db
    locations: filesystem:db/migration
    baselineOnMigrate: true
    url: jdbc:postgresql://localhost:5432/bobbysoft_organizer
